baseURL = 'https://miemiesun.github.io/newsite3/'
languageCode = 'zh'
title = '新闻探索'
theme = 'ananke'
publishDir="docs"

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true